import locale
locale.setlocale(locale.LC_NUMERIC, 'C')
#from . import normative, metadata, keymap, fstnrm, datadef, variance_misperception, empirical
#from . import early_stopping, ideal_obs
#from . import non_linear_contrast

colors = '''
*** Primary color:

   shade 0 = #D5102F = rgb(213, 16, 47) = rgba(213, 16, 47,1) = rgb0(0.835,0.063,0.184)
   shade 1 = #F3657B = rgb(243,101,123) = rgba(243,101,123,1) = rgb0(0.953,0.396,0.482)
   shade 2 = #E53B56 = rgb(229, 59, 86) = rgba(229, 59, 86,1) = rgb0(0.898,0.231,0.337)
   shade 3 = #AA051F = rgb(170,  5, 31) = rgba(170,  5, 31,1) = rgb0(0.667,0.02,0.122)
   shade 4 = #840015 = rgb(132,  0, 21) = rgba(132,  0, 21,1) = rgb0(0.518,0,0.082)

*** Secondary color (1):

   shade 0 = #E17810 = rgb(225,120, 16) = rgba(225,120, 16,1) = rgb0(0.882,0.471,0.063)
   shade 1 = #FFB46A = rgb(255,180,106) = rgba(255,180,106,1) = rgb0(1,0.706,0.416)
   shade 2 = #F3983F = rgb(243,152, 63) = rgba(243,152, 63,1) = rgb0(0.953,0.596,0.247)
   shade 3 = #B35B05 = rgb(179, 91,  5) = rgba(179, 91,  5,1) = rgb0(0.702,0.357,0.02)
   shade 4 = #8C4500 = rgb(140, 69,  0) = rgba(140, 69,  0,1) = rgb0(0.549,0.271,0)

*** Secondary color (2):

   shade 0 = #0E748B = rgb( 14,116,139) = rgba( 14,116,139,1) = rgb0(0.055,0.455,0.545)
   shade 1 = #4997A9 = rgb( 73,151,169) = rgba( 73,151,169,1) = rgb0(0.286,0.592,0.663)
   shade 2 = #2A8296 = rgb( 42,130,150) = rgba( 42,130,150,1) = rgb0(0.165,0.51,0.588)
   shade 3 = #065B6F = rgb(  6, 91,111) = rgba(  6, 91,111,1) = rgb0(0.024,0.357,0.435)
   shade 4 = #024656 = rgb(  2, 70, 86) = rgba(  2, 70, 86,1) = rgb0(0.008,0.275,0.337)

*** Complement color:

   shade 0 = #3EC00E = rgb( 62,192, 14) = rgba( 62,192, 14,1) = rgb0(0.243,0.753,0.055)
   shade 1 = #7FDE5C = rgb(127,222, 92) = rgba(127,222, 92,1) = rgb0(0.498,0.871,0.361)
   shade 2 = #5FCF36 = rgb( 95,207, 54) = rgba( 95,207, 54,1) = rgb0(0.373,0.812,0.212)
   shade 3 = #2C9904 = rgb( 44,153,  4) = rgba( 44,153,  4,1) = rgb0(0.173,0.6,0.016)
   shade 4 = #207700 = rgb( 32,119,  0) = rgba( 32,119,  0,1) = rgb0(0.125,0.467,0)


#####  Generated by Paletton.com (c) 2002-2014

'''

colors2 = '''

#####  Color Palette by Paletton.com
#####  Palette URL: http://paletton.com/#uid=34W140ktFshiJzCnJusv9mxBChx


*** Primary color:

   shade 0 = #920B92 = rgb(146, 11,146) = rgba(146, 11,146,1) = rgb0(0.573,0.043,0.573)
   shade 1 = #B049B0 = rgb(176, 73,176) = rgba(176, 73,176,1) = rgb0(0.69,0.286,0.69)
   shade 2 = #9E299E = rgb(158, 41,158) = rgba(158, 41,158,1) = rgb0(0.62,0.161,0.62)
   shade 3 = #750375 = rgb(117,  3,117) = rgba(117,  3,117,1) = rgb0(0.459,0.012,0.459)
   shade 4 = #5B005B = rgb( 91,  0, 91) = rgba( 91,  0, 91,1) = rgb0(0.357,0,0.357)

*** Secondary color (1):

   shade 0 = #0B9076 = rgb( 11,144,118) = rgba( 11,144,118,1) = rgb0(0.043,0.565,0.463)
   shade 1 = #48AD9A = rgb( 72,173,154) = rgba( 72,173,154,1) = rgb0(0.282,0.678,0.604)
   shade 2 = #289B85 = rgb( 40,155,133) = rgba( 40,155,133,1) = rgb0(0.157,0.608,0.522)
   shade 3 = #03735D = rgb(  3,115, 93) = rgba(  3,115, 93,1) = rgb0(0.012,0.451,0.365)
   shade 4 = #005948 = rgb(  0, 89, 72) = rgba(  0, 89, 72,1) = rgb0(0,0.349,0.282)

*** Secondary color (2):

   shade 0 = #E1A410 = rgb(225,164, 16) = rgba(225,164, 16,1) = rgb0(0.882,0.643,0.063)
   shade 1 = #FFD36A = rgb(255,211,106) = rgba(255,211,106,1) = rgb0(1,0.827,0.416)
   shade 2 = #F3BE3F = rgb(243,190, 63) = rgba(243,190, 63,1) = rgb0(0.953,0.745,0.247)
   shade 3 = #B38005 = rgb(179,128,  5) = rgba(179,128,  5,1) = rgb0(0.702,0.502,0.02)
   shade 4 = #8C6300 = rgb(140, 99,  0) = rgba(140, 99,  0,1) = rgb0(0.549,0.388,0)


#####  Generated by Paletton.com (c) 2002-2014

'''

def parse(colors):
    c = {}
    cname = ''
    for line in colors.splitlines():
        if line.startswith('##'): continue
        if '***' in line:
            cname = (line.replace('***', ''). replace('color:', '').replace(' ', '')
                     .replace('color', '').replace(':','').replace('(', '').replace(')',''))
            c[cname] = []
        else:
            if '#' in line:
                start = line.find('#')
                c[cname].append(line[start:start+7])
    return c


color_palette = parse(colors)
color_palette2 = parse(colors2)
